In [1]:
import sys
import os
import cv2
import numpy as np
import random
# from matplotlib import pyplot as plt
# # %matplotlib inline
# %matplotlib auto

In [2]:
frame_load_path = './mario/frames/'
path_to_output_video = './SID480365749_Asgmt2Opt1.mp4'
frame_width = 500
frame_height =500
test = cv2.imread("mario/frames/frame0.tif")
print(test)

[[[125 138  91]
  [129 141  96]
  [124 137  91]
  ...
  [160 175 149]
  [163 179 155]
  [164 180 156]]

 [[122 137  89]
  [126 141  93]
  [126 138  91]
  ...
  [162 178 151]
  [169 184 158]
  [159 175 149]]

 [[131 145 100]
  [127 141  95]
  [131 143  96]
  ...
  [163 178 152]
  [162 177 151]
  [161 177 151]]

 ...

 [[ 36  41   3]
  [ 34  38   4]
  [ 36  43   2]
  ...
  [ 65  80   6]
  [ 63  79   2]
  [ 61  77   3]]

 [[ 32  36   1]
  [ 34  40   3]
  [ 37  46   2]
  ...
  [ 59  74   3]
  [ 64  80   7]
  [ 62  77   3]]

 [[ 35  41   1]
  [ 40  49   1]
  [ 46  57   7]
  ...
  [ 53  67   5]
  [ 58  73   6]
  [ 62  76   4]]]


In [3]:
out = cv2.VideoWriter(path_to_output_video, cv2.VideoWriter_fourcc('M', 'P', '4', 'V'), 30, (int(frame_width), int(frame_height)))
frame_counter = 0
while(frame_counter<1800):
    img = cv2.imread(frame_load_path + 'frame%d.tif' % frame_counter)
    if img is None:
        print(frame_counter)
        print('No more frames to be loaded')
        break;
    out.write(img)
    frame_counter += 1
out.release()
cv2.destroyAllWindows()

584
No more frames to be loaded
